src/program/types/JSXAttribute.js, test/samples/jsx.js
*moved from https://gitlab.com/Rich-Harris/buble/merge_requests/122*
- Add `true` to output if contains dashed and non-value
- Refactor if/else into named functions
- data-attribute -> any dash-cased prop
- Add test
=> Allow truthy dash-cased props

package.json
Having package.json point at an abandoned repository is going to trip people up.
(It'd also be good if the gitlab repository could come with a big warning about the project having moved here.)
=> Point to current repository in package.json

package.json, src/index.js, test/samples/async.js
While [Rich-Harris/acorn-object-spread](/Rich-Harris/acorn-object-spread) somewhat works with acorn 5, it overwrites acorn's current implementation of parsing properties called `async` with something inferior from acorn 4. I added a test case that fails with current master and propose to switch to [my `acorn-object-spread` fork](https://github.com/adrianheine/acorn5-object-spread).
=> Switch to acorn5-object-spread

src/program/Scope.js
They are unused since abbd217027879adcbd5f6896063f24e24756c2dd.
=> Remove unused declarations from Scope.js

src/program/types/AssignmentExpression.js, src/program/types/BreakStatement.js, src/program/types/ContinueStatement.js, src/program/types/ExportDefaultDeclaration.js, src/program/types/ExportNamedDeclaration.js, src/program/types/ForOfStatement.js, src/program/types/FunctionDeclaration.js, src/program/types/FunctionExpression.js, src/program/types/ImportDeclaration.js, src/program/types/JSXOpeningElement.js, src/program/types/Literal.js, src/program/types/ObjectExpression.js, src/program/types/Super.js, src/program/types/TaggedTemplateExpression.js, src/program/types/UpdateExpression.js, src/program/types/shared/ModuleDeclaration.js, src/utils/CompileError.js
I've been hitting a problem in a `rollup` (v0.50) + `buble` (v0.16) workflow: Error messages from `buble` are replaced with something more cryptic:
```
TypeError: Cannot read property 'magicString' of undefined
at new CompileError (/.../node_modules/buble/dist/buble.umd.js:1131:29)
```
As it turns out, [`rollup` is calling the `CompileError` constructor on its own](https://github.com/rollup/rollup/blob/v0.50.0/src/utils/error.js#L8), to decorate `Error`s coming from rollup plugins. But it calls the constructor with only `message` as its first argument, triggering the aforementioned `TypeError`:
I feel that the easiest workaround is to patch `buble`'s `CompileError` constructor to be more alike the `Error` constructor.
=> Switch order of parameters for CompileError constructor

src/program/types/ObjectExpression.js, test/samples/computed-properties.js, test/samples/destructuring.js, test/samples/object-rest-spread.js
I rebased the first commit from #11 and reworked the transpilation of properties, especially computed properties, until the test in that commit and all others passed again. This should fix transpilation of a lot of non-trivial objects.
=> Destructuring computed

rollup.config.js, src/program/types/VariableDeclaration.js
Another solution to #40 (alternative to #42) — this time, just targeting Node 4, which means classes are left unmolested.
=> target node 4

src/program/Program.js, src/program/types/TaggedTemplateExpression.js, test/samples/template-strings.js
Spec tagged template literals pass the same object to each invocation of
the template tag function. This way that object can be used as a cache
key, for example, using a `Map`, so that parsing of the string contents
can be cached.
This patch changes the tagged template literal transform to declare a
frozen top-level array with the quasi strings, and passes that array to
each invocation. If this lands I think it's important to adhere to the spec re:
freezing, because otherwise people might try to attach properties to the
object itself as a sort of caching mechanism, which doesn't work in spec
tagged template literals.
I'm unsure if this is the _best_ way to declare a top-level variable,
but it seems to work OK :)
=> Reuse same object for tagged template quasis.

src/program/Scope.js, test/samples/destructuring.js
I think I'm understanding the logic introduced [here](https://github.com/Rich-Harris/buble/commit/6d9fc0ab0cd769425b026748ffa372d09b1ef35a#diff-3ada2be4c92366e1bf09caeaa19ce9c1R18).
Currently, `blockScopedDeclarations` and `aliases` are set to null within block statements, causing #60. I believe these should be objects in both `block` and `!block` cases.
Includes a minimal test that shows the issue.
=> Allow aliases in block scope

src/program/BlockStatement.js, src/program/Scope.js, src/program/types/AssignmentExpression.js, src/program/types/CallExpression.js, src/program/types/ObjectExpression.js, test/samples/computed-properties.js, test/samples/destructuring.js, test/samples/exponentiation-operator.js, test/samples/spread-operator.js
Closes #57. I also converted `CallExpression` and `AssignmentExpression` to my `Scope#createDeclaration` in two separate commits.
=> Fix which scope is used for declaring helpers for computed properties.

src/program/BlockStatement.js, test/samples/destructuring.js
Fixes #76. With this, all cases in Babel's [babel-plugin-transform-destructuring](https://github.com/babel/babel/blob/f5ef928586f592aa2d8bb60120ae58833d17e0db/packages/babel-plugin-transform-destructuring/src/index.js) are covered.
Changes the check from regex `/Function/` to an explicit list of types to transpile parameters of.
CatchClause uses `param = obj` instead of `params = [obj]`, so the `transpileParameters` function now supports both.
=> Add support for destrcturing catch clause params

src/program/types/VariableDeclaration.js, test/samples/destructuring.js
When `declarator.init` is an aliased variable, the alias wasn't looked at when choosing the name for the desctructuring.
=> Respect aliased variable names when desctructuring

src/program/types/ObjectExpression.js, test/samples/object-properties.js
it currently compiles to 
```js
var obj;
foo(( obj = {}, obj['computed'] = 1, obj.'some-var' = 2, obj ));
```
=> Handle string properties after computed properties correctly

package.json, src/program/types/JSXClosingElement.js, src/program/types/JSXClosingFragment.js, src/program/types/JSXElement.js, src/program/types/JSXFragment.js, src/program/types/JSXOpeningFragment.js, src/program/types/index.js, test/samples/jsx.js
Closes #62. This should wait for RReverser/acorn-jsx#84 and a corresponding release.
=> Implement support for JSX Fragments

package-lock.json, package.json, src/index.js, test/samples/dynamic-import.js
[dynamic import](https://github.com/tc39/proposal-dynamic-import) support has just landed in [Rollup 0.55.0](https://github.com/rollup/rollup/blob/master/CHANGELOG.md#upcoming-0550).
When testing a project that uses buble via rollup-plugin-buble, I noticed that it doesn't support dynamic import yet, resulting in the error
```
SyntaxError: Unexpected token in ...
```
Looking at the [rollup source code](https://github.com/rollup/rollup/blob/089c9e06190b894d766fc44571752fa91dc1eaa5/src/Graph.ts#L3), I see that they are using [acorn-dynamic-import](https://github.com/kesne/acorn-dynamic-import).
This pull request therefore adds the acorn-dynamic-import plugin as done in rollup itself so that buble is able to parse code that uses dynamic import.
I've also created a small test file that fails …
=> Support dynamic import

src/program/types/Literal.js, test/samples/binary-and-octal.js
Fix #74, binary and octal number literals are now properly transpired regardless uppercase or downcase base prefix
=> Fix binary octal num literals

package.json
Used here:
https://github.com/Rich-Harris/buble/blob/master/src/program/types/Literal.js#L3
=> fix: move regexpu-core out of devDependencies

src/index.js
Added the 'allowReturnOutsideFunction: true' flag.
transform(.., options) should pass acorn options, if a developer wants something specific.
Even though this goes against your 'zero config' policy, it will let users change conf without a pool request.
Please push to NPM asap, I want to use it in my code. 😄
=> should not break on a global return

.gitattributes
After an initial clone, due to my global git settings, npm install showed failing tests that were all related to a comparisons with line endings of \n failing.
Adding a .gitattributes allows git glone in windows to preserve the line endings correctly allowing the unit tests to pass - regardless of a users global git config.
=> Add .gitattributes to prevent test/lint failures in some envs

src/program/types/ArrayExpression.js, src/program/types/CallExpression.js, src/program/types/NewExpression.js, src/program/types/ObjectExpression.js, src/utils/spread.js, test/samples/computed-properties.js, test/samples/object-rest-spread.js, test/samples/spread-operator.js
My use case that leads me to desire this is code conditional on compile-time constants, e.g. `{ …, ...FEATURE ? { … } : { … } }` (with Rollup’s tree-shaking resolving the FEATURE ternary before it gets to Bublé). I first implemented what amounts to this change in Terser (https://github.com/terser-js/terser/pull/224), but then realised that I was running Bublé before Terser, and so Terser never actually *got* the spreads to inline. The next idea was running Terser, then Bublé, then Terser again… yuck. Then I decided that this optimisation really belonged in Bublé anyway: generating less code is good!
Implementation notes:
The ObjectExpression implementation was straightforward and I implemented it in situ.
Then the ArrayExpression, CallExpression and NewExpression one: at first I performed …
=> Inline spread elements where possible

src/program/types/CallExpression.js, src/utils/spread.js, test/samples/spread-operator.js
In most cases this is unnecessary, but for some expression types it is necessary, notably in ternaries; for `a ? b : c.concat(…)` is very different from `(a ? b : c).concat(…)`.
I’m not clear why the insertion of the opening parenthesis had to happen in src/program/types/CallExpression.js rather than src/utils/spread.js when start === element.start; but if I did it inside spread(), if I used appendLeft or prependLeft it’d end up like `.apply((Math, a).concat(…))` instead of `.apply(Math, (a).concat(…))`, and if I used appendRight or prependRight, nothing happened.
Fixes #177.
=> Parenthesize a first spread element when necessary

package-lock.json, package.json
Closes #183 
Care was taken to use versions of Node and NPM as discussed in https://github.com/Rich-Harris/buble/pull/184 for generating minimal changes to `package-lock.json`.
```
$ node --version
v10.15.1
$ npm --version
5.8.0
```
=> Bump magic-string

src/utils/removeTrailingComma.js, test/samples/trailing-function-commas.js
- Fixes #192 (infinite loop on commented multiline calls without trailing comma).
- Fixes #175 (revoming a comma outside the scope of a function call).
cc @adrianheine
=> Fix trailingFunctionCommas bugs

src/program/types/ObjectExpression.js, test/samples/object-properties.js
First, sorry for not creating the issue first.
I've found that bublé produces incorrect results when a string-keyed property in an object which starts with a computed property has whitespaces before colons. I added a test case for it so please take a look.
I think it's already mentioned in https://github.com/bublejs/buble/pull/91#discussion_r161163431.
=>  Fix transpiling string-keyed properties with whitespaces before colons

package-lock.json, package.json, register.js
Fixes the following warning when installing `buble` v0.19.8:
```
npm WARN deprecated os-homedir@2.0.0: This is not needed anymore. Use `require('os').homedir()` instead.
```
`os-homedir` isn't needed [since Node v2.3.0](https://nodejs.org/api/os.html#os_os_homedir).
=> Get rid of os-homedir dependency

src/program/types/ClassExpression.js, test/samples/classes.js
If the name of the subclass is identical to the name of the superclass,
use a different variable name for the superclass inside the class
function expression.
Fixes #196
=> Fix name collision in `A = class extends A {}`

src/program/types/JSXElement.js, test/samples/jsx.js
HTML only collapses normal space, tabs and newlines.
React's JSX (and Babel) traditionally also does that.
Bublé, however, has until now greedily killed all types of spaces,
except for `&nbsp;` which it turned into HTML-escaped entity,
which in turn breaks the text-node rendering in Mithril.js and Hyperscript.js.
(See #217  for more info)
=> fix: Make JSX respect advanced white-space characters (fixes #217)

src/program/BlockStatement.js, test/samples/block-scoping.js
When letConst transpilation is on, buble renames some variables, such as x->x$1. However, when shorthand properties are used, this causes the property key to change.
The appropriate fix is to make those properties no longer be shorthand, so something like `{ x : x$1 }` is used.
This applies both to object literals and object destructuring patterns.
The destructuring and concise property transpilation options hide this bug, so this commit only improves the situation for use-cases where letConst transpilation is used without those options.
=> fix: make letConst transpilation add explicit keys when appropriate

src/program/types/ForInStatement.js, test/samples/for-statement.js
When `for (a[0] in b)` is found, buble threw an error.
This commit fixes the error and adds a test.
=> Fix `handlers[node.type] is not a function` error in for...in loops.

src/program/types/ForInStatement.js, src/program/types/ForOfStatement.js, src/program/types/ForStatement.js, src/program/types/shared/LoopStatement.js, test/samples/block-scoping.js
This fixes an issue encountered when compiling:
```
for (let i = 0; i < 10; i++) {
const i = ...;
...
}
```
Buble incorrectly threw an error due to the 'i' in 'i++' being
incorrectly identified as a constant.
This commits makes it so for, for in and for of loops have their
own scope.
The way the variable declarations are handled to calculate `shouldRewriteAsFunction` is not ideal. It only got the bare minimum changes to pass the existing tests, so current limitations still apply.
=> Fix scoping of variables declared in for loops.

src/program/types/Identifier.js, test/samples/loops.js
When a label has the same name as a variable that has been renamed due to let/const transpilation, the label may also be renamed.
This should not happen, since labels do not follow the same scope rules as variables.
This commit prevents labeled continues and label statements from being renamed, fixing the issue.
Labeled break were not buggy, as breaks do not initialise their children anyway, but this commit also adds breaks to the list of renames to skip, for consistency.
See the added tests for examples that were previously buggy.
=> Prevent labels from being renamed due to let/const transpilation.

scripts/test262-data.js, src/program/types/CatchClause.js, src/program/types/index.js, test/samples/misc.js
Buble did not recognize variables declared in catch clauses, causing the code in the added unit test to fail to compile.
=> Fix recognition of catch-declared variables

src/program/types/ObjectExpression.js, test/samples/computed-properties.js, test/samples/destructuring.js, test/samples/object-rest-spread.js
The new implementation has less code, more comments, and passes more
tests.
The design of the algorithm is detailed in comments; the only major
change to note is that the output has changed to be more conservative
with object creation. For example, `x = { ...a, b }` now compiles to
`x = Object.assign({}, a); x.b = b`
instead of
`x = Object.assign({}, a, {b: b})`
So generated programs that previously executed without problems may be
different now, although they will hopefully still execute without
problems.
---
GitHub doesn't display this diff very well; more of this code is unchanged than is evident. In particular, the block with all the TODO comments is untouched from the original. Whatever bugs lie in wait there, I probably didn't make them worse.
Fixes #163, fixes #203, fixes #212.
=> Rewrite ObjectExpression transpilation
